language: php

php:
  - 5.5
  - 5.6

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

services: mongodb

before_install:
    - composer self-update

install:
    - composer --prefer-source install

notifications:
  email:
    - payumsupport@forma-pro.com